### ISSUE TITLE
Unable to resolve "./../elements/SafeAreaDecider" from "node_modules\react-native-form-prorgress\index.js"

### ISSUE THREAD

**Issue by scroobius-pip** [blendtale/react-native-form-progress#3]
I'm getting this error, i think you forgot to include that folder

**Comment by irohitb** [comment]
@scroobius-pip fixed it. Can you re-install or update the package and confirm if it is working for you?

**Comment by irohitb** [comment]
Version 1.0.4 should fix, if not please create a new issue. Marking this closed now :)
